### ISSUE TITLE
Close Chrome tab after validating API

### ISSUE THREAD

**Issue by mrkaye97** [orcasgit/python-fitbit#153]
Hey,

I dug around in the code a little but couldn't find it. Is there a way to automate closing the tab that opens when you go to validate the permissions for the API? Would be nice to not need to close the tab every time.

Thanks!

**Comment by bikramb98** [comment]
Any idea about this?

**Comment by mrkaye97** [comment]
> Any idea about this?

Nope, still nothing

**Comment by MiniXC** [comment]
This could be done using javascript.
Currently ``gather_keys_oauth2.py`` uses the following:
````
self.success_html = """
            <h1>You are now authorized to access the Fitbit API!</h1>
            <br/><h3>You can close this window</h3>
            """
````
Instead, you could just use
````
self.success_html = """
            <script>window.close();</script>
            """
````
