### ISSUE TITLE
[INFO] Repo not maintained anymore ?

### ISSUE THREAD

**Issue by chemelli74** [orcasgit/python-fitbit#169]
Seems this repo is not maintained any more; should we make a fork of this library to improve it ?

Simone

**Comment by brad** [comment]
Yes

**Comment by chemelli74** [comment]
@GhostofOnyx238, what do you think about taking over ?

Simone

**Comment by Ziip-dev** [comment]
I vote for it too :)
I have been working with this project for a while but it is a bit of struggle actually

**Comment by j-rossi-nl** [comment]
@chemelli74
Very late to this party.
What does "taking over" imply? Did you already start dev on your own fork?

I would be interested in co-owning it with at least 1 or 2 others. 
I see a lot of work needing to be done, wrt coverage of the API.
Also using the Swagger description of the API to build the package.

Let's not forget: we need to contact Fitbit so their developer website points to our repo and not to this one.

**Comment by chemelli74** [comment]
@j-rossi-nl didn't start doing anything yet.

If you agree, you can start a fork and then we will work together on it ;-)
Hopefully, others will join.

Simone

**Comment by Ziip-dev** [comment]
I would also like to join you guys to give a hand on this :)
Only a hobbyist developer, so no professional expertise on my side but I'd love to improve and learn more about open source co-development.

I have extensively used Fitbit WEB API as well as this library during my phd work, and I already started to work on the upgrade of their [second project](https://github.com/orcasgit/django-fitbit) to Django 4 + Python 3.10, which integrates python-fitbit into a ready-to-work Django app

**Comment by chemelli74** [comment]
Thinking about it again, do you mind if we create the repo on https://github.com/home-assistant-libs ?

Simone

**Comment by Ziip-dev** [comment]
In my opinion we are changing the displayed purpose of the library and diluting information doing this, as this is basically independent from any home automation solution.

**Comment by chemelli74** [comment]
Ok, no problem. Let's go with an independent repo then.

Let me know if one of you create it or I do.

Simone

**Comment by j-rossi-nl** [comment]
Fine, I forked it yesterday (I wanted to retrieve the TCX files, and it's not covered in the current code. I quickly made a PR and then I found out your issue :) ).
The fork is here: https://github.com/j-rossi-nl/python-fitbit 

I'll add you as collaborators: @chemelli74 @Ziip-dev

**Comment by chemelli74** [comment]
I think we need to change the name or we won't be able to release because of the conflict.
Maybe "`pyfitbit`" or similar.

Simone

**Comment by Ziip-dev** [comment]
Either this or asking the original developer to remove the abandoned project from PyPi.
Even if there is no hurry, I'm not sure of the time that could take though

**Comment by j-rossi-nl** [comment]
I'll put this as an issue in the fork.

**Comment by chemelli74** [comment]
New repo active: https://github.com/j-rossi-nl/py-fitbit
