### ISSUE TITLE
Specifying a start or end time of midnight for intraday_time_series causes a TypeError

### ISSUE THREAD

**Issue by donaghhorgan** [orcasgit/python-fitbit#56]
If you call the `intraday_time_series` method and specify a start time or end time of midnight (i.e. 00:00), a TypeError is thrown. Minimum working example:

```
import fitbit
from datetime import time
from secrets import consumer_key, consumer_secret, user_key, user_secret

client = fitbit.Fitbit(consumer_key, 
                       consumer_secret, 
                       resource_owner_key=user_key, 
                       resource_owner_secret=user_secret)
client.intraday_time_series("activities/steps", start_time=time(0,0), end_time=(23,59))
```

This behaviour is caused by lines 376 and 379 of api.py, i.e.

```
if start_time and not end_time:
    raise TypeError("You must provide an end time when you provide a start time")

if end_time and not start_time:
    raise TypeError("You must provide a start time when you provide an end time")
```

The problem is that if `start_time = time(0,0)`, then it evaluates to `False` as a boolean (the same goes for `end_time`) so the check `if start_time and ...` will always evaluate to `False`. I think the idea here is to check that `start_time` is not equal to `None`, so the fix here should be pretty simple:

```
if start_time is not None and end_time is None:
    raise TypeError("You must provide an end time when you provide a start time")

if end_time is not None and start_time is None:
    raise TypeError("You must provide a start time when you provide an end time")
```

**Comment by brad** [comment]
Fixed in 81428b9c01f459f88d934a8aeecbd461dd28c472

**Comment by avinash-keshri** [comment]
hi donaghhorgan, can you pls tell me how you got  'user_key' and 'user_secret' . i am unable to find it via ./gather_keys_cli.py file. Thanks in advance.

**Comment by avinash-keshri** [comment]
Able to fetch the keys. thanks
