### ISSUE TITLE
OAuth 2.0 support

### ISSUE THREAD

**Issue by randi120** [orcasgit/python-fitbit#59]
Hello, 
Was wondering if OAuth 2.0 support was in the pipeline? 
https://wiki.fitbit.com/display/API/OAuth+2.0

**Comment by brad** [comment]
Hi @randi120 
I didn't realize they had added Oauth 2.0 support! It is not something we are currently working on, but we will happilly accept pull requests :smile:

**Comment by randi120** [comment]
almost there on first pass. expect pull request within a day

**Comment by brad** [comment]
That's great news!

**Comment by randi120** [comment]
pull request created. 

there are a few things that should be cleaned up, mostly error handling.  the token storage could be streamlined... 
let me know if something is not clear.

**Comment by brad** [comment]
Implemented with PR #61
