### ISSUE TITLE
Heart rate based on OAuth 2.0

### ISSUE THREAD

**Issue by robertheinze** [orcasgit/python-fitbit#60]
Hi!
Fitbit released OAuth 2.0 which is the base to retrieve Heart Rate data as far as I have understood it. Could you please integrate this OAuth 2.0 procedure. I am currently running it like shown, but I don't get heart rate!
![robertheinze_ _pi_raspberrypi____downloads_benallard-galileo-65f67e191699_galileo_ _ssh_ _128x37](https://cloud.githubusercontent.com/assets/12094678/7784235/c74828ae-015e-11e5-89de-05918d92e809.png)

**Comment by brad** [comment]
Hi @robertheinze thank you for your request! We have already received a request for OAuth 2.0 support in #59 so I am going to close this issue. Please subscribe to that issue for updates.

**Comment by robertheinze** [comment]
Thanks Brad, looking forward to the implementation :)

**Comment by abhijitpatkar** [comment]
Hi @robertheinze i have one question for you.In the #constants from where you get USER_KEY and USER_SECRET keys?.if you can explain detail steps to generate USER_KEY and USER_SECRET it will be very helpful 
Thanks...

**Comment by abhijitpatkar** [comment]
Hi @robertheinze i have one question for you.In the #constants from where you get USER_KEY and USER_SECRET keys?.if you can explain detail steps to generate USER_KEY and USER_SECRET it will be very helpful 
Thanks...
