### ISSUE TITLE
gather_keys_oauth2

### ISSUE THREAD

**Issue by robertheinze** [orcasgit/python-fitbit#65]
I don’t know why but my gather_keys_oauth2.py stands still with “Bus STARTED” forever.
What parameters do you call it with? Client (Consumer) Key and the Client (Consumer) Secret-is this correct? Are there any other precautions to be done?

**Comment by brad** [comment]
@robertheinze Are you running it on a server? It has to be run on a machine with a display so it can open a web browser.

**Comment by robertheinze** [comment]
@brad  Yes, this was the reason, thanks for your quick response

**Comment by avinash-keshri** [comment]
@robertheinze are you able to get the 'user_key' ,'user_secret' that is to be used in

**Comment by avinash-keshri** [comment]
@robertheinze Are you able to get the 'user_key' and 'user_secret' to be used in below code:

authd_client = fitbit.Fitbit('consumer_key', 'consumer_secret', resource_owner_key='user_key', resource_owner_secret='user_secret')

If yes, can you pls tell me the steps to fetch those. Thanks in advance.

**Comment by avinash-keshri** [comment]
Able to fetch the keys. Thanks
