### ISSUE TITLE
Problem getting intraday HR from Charge HR

### ISSUE THREAD

**Issue by robertheinze** [orcasgit/python-fitbit#66]
Hi Brad, me again - sorry

I want to read out the HR from Fitbit Charge HR but I always run into this ...
Traceback (most recent call last):
  File "fitbit_heartrate.py", line 12, in <module>
    intradayH = authd_client.intraday_time_series('activities/heart', base_date = 'today', detail_level = '1min')
  File "/usr/local/lib/python2.7/dist-packages/fitbit-0.1.3-py2.7.egg/fitbit/api.py", line 389, in intraday_time_series
    return self.make_request(url)
  File "/usr/local/lib/python2.7/dist-packages/fitbit-0.1.3-py2.7.egg/fitbit/api.py", line 201, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fitbit-0.1.3-py2.7.egg/fitbit/api.py", line 96, in make_request
    raise HTTPBadRequest(response)
fitbit.exceptions.HTTPBadRequest: Resource owner is required

I am calling it like:
import fitbit
import json

CLIENT_KEY = '7644256......99106bc0d90e'
CLIENT_SECRET = '87eacfb......6ac33c91e1'
ACCESS_TOKEN = 'eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0......x7tDE1Y6SB7q3c_Mrc'
REFRESH_TOKEN = 'cac2ebab561434178fa104f.....027553eb6fde84df4db49af060'

authd_client = fitbit.Fitbit(CLIENT_KEY, CLIENT_SECRET, oauth2=True, access_token=ACCESS_TOKEN, refresh_token=REFRESH_TOKEN)

intradayH = authd_client.intraday_time_series('activities/heart', base_date = 'today', detail_level = '1min')

f = open('datadumpHeart.json', 'w')
json.dump(intradayH, f)

Do you have an idea for this?
Thanks
Robert

**Comment by Packetslave** [comment]
Is your registered Fitbit application approved for partner API access?  Unless it is, you can't get intraday data.  Your code works as written for me, using my client ID and secret is authorized for partner access.

**Comment by robertheinze** [comment]
very strange, they changed to parter API access, it still doesn't work and now I tried the gather_keys_oauth2.py again with the http://127.0.0.1:8080 redirect_url set and the dev.fitbit.com shows "invalid_request : invalid redirect_url param value" 
it is really a pain in the a...

**Comment by brad** [comment]
@robertheinze I was able to reproduce the error you reported by using `http://127.0.0.1:8080` in the "Callback URL" field, but when I add a trailing slash (`http://127.0.0.1:8080/`) it works. Can you please try that?

**Comment by robertheinze** [comment]
@brad Thanks the 8080/ made it.
I still get the errors mentioned in the issue, but I think that FitBit granted robert.heinze@me.com the Partner API rights wrong. So I contacted them again. I'll let you know.

**Comment by robertheinze** [comment]
According to Fitbit I have Partner API rights but I still get the error message posted at the beginning of this issue.

**Comment by robertheinze** [comment]
Finally fixed it.
Reinstalled python-titbit and ran for new tokens, now it works
