### ISSUE TITLE
I can not get the library to use OAuth2.

### ISSUE THREAD

**Issue by lordmikefin** [orcasgit/python-fitbit#69]
Hi,

I'm implementing Fitbit data fetching to our application.

While I was looking for how to do this I noticed your great library.

I have been testing you library today (just today).

I installed library with command 'easy_install fitbit' and it started to work.
After few testing I started to look how to actually gather the tokens.
I noticed from your documents that you have code to get tokens, but not much guides how to do this.
So I cloned your code and I found out that you have really nice example code in file 'gather_keys_oauth2.py'.

Now I have implemented similar procedure in my app.

I encountered problem while trying to use the tokens.
authd_client = fitbit.Fitbit(
				consumer_key, #'<consumer_key>', 
				consumer_secret, #'<consumer_secret>', 
				oauth2=True,
				access_token=token.get('access_token'), #<token>, 
				refresh_token=token.get('refresh_token') #<token>)

authd_client.client is <fitbit.api.FitbitOauthClient object at 0x645bfd0>

It seems that setting 'oauth2=True' does not do anything.

After while I decided just use your code in my code (so I'm not using the library).
And now it works !!!!!!

It seems there is some problem with binary file (https://pypi.python.org/pypi/fitbit/0.1.3).

**Comment by lordmikefin** [comment]
authd_client.client object type is 'FitbitOauthClient'

**Comment by brad** [comment]
@lordmikefin Version 0.1.3 does not support OAuth2. If you would like to use OAuth2 at the moment, you will need to install from git.
