### ISSUE TITLE
need to reauth too often?

### ISSUE THREAD

**Issue by kevingoldsmith** [orcasgit/python-fitbit#76]
I'm a bit of an oauth2 noob, so sorry if this is a moronic question. 

Using the branch with the oauth2 fix, I'm grabbing the credentials and storing them in a config file. Then I'm loading them when I want to access the API. I've got some code to download all the user's fitbit history (based on the old dump.py example). When I hit the API rate limit, I wait until the next hour, but at that time my tokens have expired. I thought that the API itself should be handling this case...

**Comment by brad** [comment]
Not a moronic question. :smile: I'm not very familiar with it either, but according to the docs, access tokens have a lifespan of only one hour and applications are expected to refresh the token before then. I think we will include auto refresh support in the django library (using celery tasks) but I can't think of a great way to support auto refresh at the level of this library. We are happy to accept pull requests :smile: Regarding your problem with token expiration, I think this suggestion from the [Fitbit docs](https://dev.fitbit.com/docs/oauth2/#refreshing-tokens) might help:

> Alternatively, your application could redirect the user to the authentication flow. If the user is signed in and the scopes requested match the previously granted scopes, the user will be redirected to your callback URI with a new access token without being prompted.

**Comment by kevingoldsmith** [comment]
Thanks for the answer. Is there a way to manually refresh through the API? I could detect the case where the refresh limit would be so long that the tokens would get invalidated and do a manual refresh mid-way to avoid the problem...

**Comment by brad** [comment]
@karthikbgl Yes, if `fitbit` is your api object, you can do `fitbit.client.refresh_token()`

**Comment by brad** [comment]
Sorry @karthikbgl I meant @kevingoldsmith

**Comment by kevingoldsmith** [comment]
sweet!

**Comment by SVendittelli** [comment]
@kevingoldsmith How is it that you are grabbing the credentials? I'm trying to store them in a config also but can figure out how. Is it just a case of manually refreshing them and getting them then?

**Comment by brad** [comment]
@kevingoldsmith Can we close this?

**Comment by kevingoldsmith** [comment]
go ahead and close. thanks!

**Comment by kevingoldsmith** [comment]
@SVendittelli see my (un-merged PR): https://github.com/orcasgit/python-fitbit/pull/80/files Also @brad is there anything I need to do for it to be merged, or if you don't think it is useful, that is fine, too. It's been sitting for a while...
