### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jberge** [orcasgit/python-fitbit#83]
I am a novice, and I am having trouble importing Fitbit library. Getting import errors with init.py and api.py. Running Python 2.7.11 on a Windows 10 machine. Funny thing is the import is working fine on a Windows 7 machine running Python 2.7.6. Any suggestions other than setting up virtualenv?

**Comment by brad** [comment]
@jberge We need more information. Can you please comment with the content of the error? The error your getting sounds like you may be missing a dependency. All the dependencies needed are listed in `requirements/base.txt` and can be installed using `pip`.

**Comment by jberge** [comment]
![image](https://cloud.githubusercontent.com/assets/13355223/12897719/e40a482e-ce5d-11e5-8b44-12f3f14d7ae4.png)

I hope you can see a screen grab of the error.  Pip was installed as part of python 2.7.11 install.

**Comment by brad** [comment]
@jberge Yep, so that confirms your error is because you are missing the `requests` library, which gets pulled in as part of our `requests-oauthlib` requirement. You can get all the dependencies by running `pip install -r requirements/base.txt`. Best practice is to do that with virtualenv but it can also be done with the global python environment.

**Comment by jberge** [comment]
That did it.  Thank you so much for your help!

**Comment by brad** [comment]
No problem! :+1:

**Comment by jberge** [comment]
![image](https://cloud.githubusercontent.com/assets/13355223/12899692/6d2e7e50-ce67-11e5-86ae-24ef5f50c70e.png)

I installed the requests library as suggested.  I was receiving a warning saying I should use of new version of pip.  Is that recommended with python 2.7.11?

**Comment by brad** [comment]
Absolutely, I always recommend using the latest version of pip.

**Comment by jberge** [comment]
Thank you so much!
